services:
  - type: web
    name: code-review-bug-generator
    env: docker
    plan: free
    branch: main
    autoDeploy: true
    dockerfilePath: ./Dockerfile
    envVars:
      - key: API_KEY
        scope: build,runtime
      - key: JWT_SECRET_KEY
        scope: build,runtime

  - type: redis
    name: code-review-redis
    plan: free
    region: oregon
    maxmemoryPolicy: noeviction